apiVersion: apps/v1
kind: Deployment
metadata:
  name: memberservices-api-staging
  namespace: memberservices-gitops-staging
  labels:
    app: memberservices-api
    environment: staging
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: memberservices-api
      environment: staging
  template:
    metadata:
      labels:
        app: memberservices-api
        environment: staging
        version: v1
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: memberservices-api
        image: fbdevygfwoiacr.azurecr.io/farmersbank/memberservices:${{ github.sha }}
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 5001
          name: grpc
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Staging"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: memberservices-api-service-staging
  namespace: memberservices-gitops-staging
  labels:
    app: memberservices-api
    environment: staging
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: grpc
    port: 5001
    targetPort: 5001
    protocol: TCP
  selector:
    app: memberservices-api
    environment: staging
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: memberservices-api-hpa-staging
  namespace: memberservices-gitops-staging
  labels:
    app: memberservices-api
    environment: staging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: memberservices-api-staging
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80